sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: aa128360877
  redis:
    host: localhost
    port: 6379
    password: aa128360877
    database: 10